name: notes_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cloud_firestore: ^5.5.0
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  fluttertoast: ^8.2.8
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.3
  crypto: 3.0.2


dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/poppins_bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/poppins_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/poppins/poppins_medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/poppins_regular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
